name: PandoraTopp
favicon: null
layout_spectrum: 0.38275902648456395
typography_spectrum: 0.68863
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030305'
    - '#f9feff'
    - '#c0c0be'
    - '#7f6a53'
    - '#442940'
  brandStrength: 0.6791319467592984
  lightness: 0.6224955832585692
  saturation: 0.5427015791647136
  rhythmicContrast: 0.9457380485255271
purpose: []
